<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-300BKIO" failures="1" tests="10" name="memberSmokeTest.memberSignInTest" time="64.062" errors="0" timestamp="2024-03-01T16:44:19 IST" skipped="0">
  <testcase classname="memberSmokeTest.memberSignInTest" name="memberHomePageTitleTest" time="0.434"/>
  <testcase classname="memberSmokeTest.memberSignInTest" name="memberSignInURLTest" time="0.347"/>
  <testcase classname="memberSmokeTest.memberSignInTest" name="signInbyValidEmail" time="15.833"/>
  <testcase classname="memberSmokeTest.memberSignInTest" name="signInbyvalidMobile" time="13.664"/>
  <testcase classname="memberSmokeTest.memberSignInTest" name="signInByInvalidmail" time="7.586"/>
  <testcase classname="memberSmokeTest.memberSignInTest" name="signInByInvalidMobile" time="7.759"/>
  <testcase classname="memberSmokeTest.memberSignInTest" name="signInByWrongMailFormat" time="0.926"/>
  <testcase classname="memberSmokeTest.memberSignInTest" name="signInByWrongPhoneFormat" time="4.170"/>
  <testcase classname="memberSmokeTest.memberSignInTest" name="signInForgotPassByInvalidmail" time="8.829"/>
  <testcase classname="memberSmokeTest.memberSignInTest" name="signInForgotPassByInvalidPhone" time="4.514">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at memberSmokeTest.memberSignInTest.signInForgotPassByInvalidPhone(memberSignInTest.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- signInForgotPassByInvalidPhone -->
</testsuite> <!-- memberSmokeTest.memberSignInTest -->
